apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ruby-http
spec:
  source:
    repoURL: https://github.com/Dhaamodharan/ruby_helm.git
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ruby-http
  project: default
  syncPolicy:
    automated: {}
